# Generated by Django 5.1.1 on 2024-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_rename_user_tguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('barista', 'Barista')], default='buyer', max_length=10),
        ),
    ]
