# Generated by Django 5.1.1 on 2024-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('barista', 'Barista')], default='customer', max_length=10),
        ),
    ]
