# Generated by Django 5.1.1 on 2024-09-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0006_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonus.tguser'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('barista', 'Barista')], default='customer', max_length=10),
        ),
    ]
