# Generated by Django 5.1.1 on 2024-09-29 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0007_alter_order_user_alter_tguser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bonus.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.product')),
            ],
        ),
    ]
