"""
Django settings for zxc project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g8jhc#!t3$v4*kaalcfti=7-$0zek8u5&#n6v=5tfp#=b5*&54'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'bot.apps.BotConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zxc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zxc.wsgi.application'
ASGI_APPLICATION = 'zxc.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'zxc_cafe',
        'USER': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TELEGRAM_API_ID = 21382300
TELEGRAM_API_HASH = 'ae81aa2cbccae4a3056bf3f2e971f8e2'
TELEGRAM_BOT_TOKEN = '7340654169:AAFROeMfOTwOz-t03IX_srS671PQRq1Dj-g'

ADMIN_USER_IDS = [216402265]
BARISTA_USERNAMES = ['vcorobceanu']

# uvicorn zxc.asgi:application --host 0.0.0.0 --port 8011


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {  # root logger
            'handlers': ['console'],
            'level': 'INFO',  # Set to DEBUG to capture all logs
        },
    },
}

UNFOLD = {
    'SITE_TITLE': 'Coffee Shop Admin',
    'SITE_HEADER': 'Coffee Shop Administration',
    'INDEX_TITLE': 'Dashboard',
    'LOGIN_LOGO': 'img/login_logo.png',
    'MAIN_LOGO': 'img/main_logo.png',
    'FAVICON': 'img/favicon.ico',
    'SHOW_COLLAPSE': True,
    'SHOW_QUICK_FILTER': True,
    'ENABLE_CHARTS': True,
    'CUSTOM_CSS': 'css/custom_admin.css',
    'CUSTOM_JS': 'js/custom_admin.js',
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    'MENU': [
        {'label': 'Dashboard', 'url': '/admin/', 'icon': 'fa-home'},
        {'label': 'Orders', 'model': 'your_app.Order', 'icon': 'fa-shopping-cart'},
        {'label': 'Products', 'model': 'your_app.Product', 'icon': 'fa-coffee'},
        {'label': 'Customers', 'model': 'your_app.Customer', 'icon': 'fa-users'},
    ],
    "DASHBOARD_CALLBACK": "bot.views.dashboard_callback",
    'DASHBOARD_CHARTS': [
        {
            'title': 'Today\'s Orders',
            'chart_type': 'line',
            'data_source': 'bot.admin_utils.get_todays_orders_chart_data',
            'options': {
                'scales': {
                    'xAxes': [{
                        'type': 'time',
                        'time': {
                            'unit': 'hour',
                            'displayFormats': {
                                'hour': 'HH:mm',
                            },
                        },
                        'distribution': 'linear',
                    }],
                    'yAxes': [{
                        'ticks': {
                            'beginAtZero': True,
                            'stepSize': 1,
                        },
                    }],
                },
                'responsive': True,
            },
        },
    ],

}
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR, 'media'

LOGIN_URL = 'admin:login'
LOGOUT_URL = 'admin:logout'
