# Generated by Django 5.1.1 on 2024-10-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coffees_free',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.order'),
        ),
    ]
