# Generated by Django 5.1.1 on 2024-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_customer_coffees_free_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_drinks',
            field=models.IntegerField(default=0),
        ),
    ]
