# Generated by Django 5.1.1 on 2024-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_order_free_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
