# Generated by Django 5.1.1 on 2024-10-15 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created', to='bot.customer'),
        ),
    ]
