# Generated by Django 5.1.1 on 2024-10-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_order_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
